server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdemodb
    username: springdemouser
    password: springdemouser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health, features"

